#!/usr/bin/env bash
# gen-rung0-digest.sh — emit the rung-0 lint-rule digest for a project.
#
#   gen-rung0-digest.sh <project-dir> [output-file]
#
# Rung-0 rules are the ones no mechanism yet catches, so the agent must hold
# them in context. Rung-1+ rules are enforced by clippy/tests and cost the agent
# nothing — they are deliberately EXCLUDED here. The digest therefore *shrinks*
# as rules graduate: the whole point of the framework.
#
# Source of truth is the target's committed `rules` root. Default output is
# <project>/.kinora/rung0-hints.md. Regenerate after any rule is added or
# graduated (e.g. from /jig sync rust, or by hand).
set -euo pipefail

TARGET="${1:-}"
if [ -z "$TARGET" ]; then
  echo "usage: gen-rung0-digest.sh <project-dir> [output-file]" >&2
  exit 2
fi
OUT="${2:-$TARGET/.kinora/rung0-hints.md}"

if ! command -v kinora >/dev/null 2>&1; then
  echo "error: kinora is not on PATH — enable the kinora jig and run 'nix develop'." >&2
  exit 1
fi
if [ ! -d "$TARGET/.kinora" ]; then
  echo "error: no .kinora/ under $TARGET." >&2
  exit 1
fi

# ── enumerate active rung-0 rules from the committed `rules` root ─────────────
# COUPLING: this reads kinora's committed root styxl directly (one member per
# line: `{id …, metadata {name …, rule::rung N, …, status::active true}, …}`),
# because the CLI has no list/query yet. When kinora gains one, replace only
# this function.
rung0_rule_names() {
  local ptr="$TARGET/.kinora/roots/rules"
  [ -f "$ptr" ] || return 0
  local hash blob
  hash="$(cat "$ptr")"
  blob="$TARGET/.kinora/store/${hash:0:2}/${hash}.styxl"
  [ -f "$blob" ] || return 0
  # Skip the header line ({kind root …}); emit the name of every member whose
  # metadata has `rule::rung 0` and `status::active true`.
  awk '
    /^\{kind root/ { next }
    /rule::rung 0[,}]/ && /status::active true/ {
      # Anchor to the metadata block so a stray earlier `name ` token (e.g. in a
      # note field) can never be picked up. "metadata {name " is 15 chars.
      if (match($0, /metadata \{name [^,}]+/)) {
        n = substr($0, RSTART + 15, RLENGTH - 15)
        gsub(/[[:space:]]+$/, "", n)
        print n
      }
    }
  ' "$blob"
}

# First paragraph of a rule body (its statement), for the digest. Capturing the
# resolve output with `|| true` keeps a rule that fails to resolve from aborting
# the whole run under `set -euo pipefail` — it just yields an empty statement.
statement_of() {
  local body
  body="$(kinora -C "$TARGET" resolve "$1" 2>/dev/null || true)"
  printf '%s\n' "$body" \
    | sed 's/\x1b\[[0-9;]*m//g' \
    | awk 'NR==1 && /^# / { next } /^#/ { next } NF { print; got=1; next } got { exit }'
}

mapfile -t NAMES < <(rung0_rule_names | sort)

# ── write the digest ─────────────────────────────────────────────────────────
{
  echo "<!-- generated by gen-rung0-digest.sh — do not edit; regenerate after rule changes -->"
  echo
  echo "# Active lint rules (rung 0)"
  echo
  if [ "${#NAMES[@]}" -eq 0 ]; then
    echo "None — every active rule is mechanized (rung 1+). The toolchain catches"
    echo "violations; you don't need to hold any rule in context."
  else
    echo "These rules are **not yet caught by any mechanism**, so follow them directly."
    echo "Rung-1+ rules are enforced by clippy/tests — you don't hold those in context."
    for n in "${NAMES[@]}"; do
      echo
      echo "## $n"
      echo
      statement_of "$n"
    done
  fi
} > "$OUT"

echo "wrote $OUT (${#NAMES[@]} rung-0 rule(s))"
